# =============================================== Cortical and Subcortical Labels ===============================================

CORT_LABELS = [
    "void",
    "frontal pole",
    "insular cortex",
    "superior frontal gyrus",
    "middle frontal gyrus",
    "inferior frontal gyrus, pars triangularis",
    "inferior frontal gyrus, pars opercularis",
    "precentral gyrus",
    "temporal pole",
    "superior temporal gyrus, anterior division",
    "superior temporal gyrus, posterior division",
    "middle temporal gyrus, anterior division",
    "middle temporal gyrus, posterior division",
    "middle temporal gyrus, temporooccipital part",
    "inferior temporal gyrus, anterior division",
    "inferior temporal gyrus, posterior division",
    "inferior temporal gyrus, temporooccipital part",
    "postcentral gyrus",
    "superior parietal lobule",
    "supramarginal gyrus, anterior division",
    "supramarginal gyrus, posterior division",
    "angular gyrus",
    "lateral occipital cortex, superior division",
    "lateral occipital cortex, inferior division",
    "intracalcarine cortex",
    "frontal medial cortex",
    "juxtapositional lobule cortex",
    "subcallosal cortex",
    "paracingulate gyrus",
    "cingulate gyrus, anterior division",
    "cingulate gyrus, posterior division",
    "precuneous cortex",
    "cuneal cortex",
    "frontal oribtal cortex",
    "parahippocampal gyrus, anterior division",
    "parahippocampal gyrus, posterior division",
    "lingual gyrus",
    "temporal fusiform cortex, anterior division",
    "temporal fusiform cortex, posterior division",
    "temporal occipital fusiform cortex",
    "occipital fusiform gyrus",
    "frontal operculum cortex",
    "central opercular cortex",
    "parietal operculum cortex",
    "planum polare",
    "heschls gyrus",
    "planum temporale",
    "supracalcarine cortex",
    "occipital pole",
]

SUB_LABELS = [
    "void",
    "left cerebral white matter",
    "left cerebral cortex",
    "left lateral ventrical",
    "left thalamus",
    "left caudate",
    "left putamen",
    "left pallidum",
    "brain-stem",
    "left hippocampus",
    "left amygdala",
    "left accumbens",
    "right cerebral white matter",
    "right cerebral cortex",
    "right lateral ventricle",
    "right thalamus",
    "right caudate",
    "right putamen",
    "right pallidum",
    "right hippocampus",
    "right amygdala",
    "right accumbens",
]
